frase = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome....')
print('Seu nome em maiusculo é {}'.format(frase.upper()))
print('Seu nome em minuscula é {}'.format(frase.lower()))
print('Seu nome tem ao todo {} letras'.format(len(frase) - frase.count(' ')))
# print('E seu primeiro tem {} letras'.format(frase.find(' ')))
separa = frase.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
